class Country {
  final String name;
  final String capital;

  const Country({required this.name, required this.capital});
}

const List<Country> capitals = [
  Country(name: 'Afghanistan', capital: 'Kabul'),
  Country(name: 'Albania', capital: 'Tirana'),
  Country(name: 'Algeria', capital: 'Algiers'),
  Country(name: 'Andorra', capital: 'Andorra la Vella'),
  Country(name: 'Angola', capital: 'Luanda'),
  Country(name: 'Antigua and Barbuda', capital: 'Saint John\'s'),
  Country(name: 'Argentina', capital: 'Buenos Aires'),
  Country(name: 'Armenia', capital: 'Yerevan'),
  Country(name: 'Australia', capital: 'Canberra'),
  Country(name: 'Austria', capital: 'Vienna'),
  Country(name: 'Azerbaijan', capital: 'Baku'),
  Country(name: 'Bahamas', capital: 'Nassau'),
  Country(name: 'Bahrain', capital: 'Manama'),
  Country(name: 'Bangladesh', capital: 'Dhaka'),
  Country(name: 'Barbados', capital: 'Bridgetown'),
  Country(name: 'Belarus', capital: 'Minsk'),
  Country(name: 'Belgium', capital: 'Brussels'),
  Country(name: 'Belize', capital: 'Belmopan'),
  Country(name: 'Benin', capital: 'Porto-Novo'),
  Country(name: 'Bhutan', capital: 'Thimphu'),
  Country(name: 'Bolivia', capital: 'Sucre'),
  Country(name: 'Bosnia and Herzegovina', capital: 'Sarajevo'),
  Country(name: 'Botswana', capital: 'Gaborone'),
  Country(name: 'Brazil', capital: 'Brasília'),
  Country(name: 'Brunei', capital: 'Bandar Seri Begawan'),
  Country(name: 'Bulgaria', capital: 'Sofia'),
  Country(name: 'Burkina Faso', capital: 'Ouagadougou'),
  Country(name: 'Burundi', capital: 'Gitega'),
  Country(name: 'Cabo Verde', capital: 'Praia'),
  Country(name: 'Cambodia', capital: 'Phnom Penh'),
  Country(name: 'Cameroon', capital: 'Yaoundé'),
  Country(name: 'Canada', capital: 'Ottawa'),
  Country(name: 'Central African Republic', capital: 'Bangui'),
  Country(name: 'Chad', capital: 'N\'Djamena'),
  Country(name: 'Chile', capital: 'Santiago'),
  Country(name: 'China', capital: 'Beijing'),
  Country(name: 'Colombia', capital: 'Bogotá'),
  Country(name: 'Comoros', capital: 'Moroni'),
  Country(name: 'Congo (Republic of the)', capital: 'Brazzaville'),
  Country(name: 'Congo (Democratic Republic of the)', capital: 'Kinshasa'),
  Country(name: 'Costa Rica', capital: 'San José'),
  Country(name: 'Croatia', capital: 'Zagreb'),
  Country(name: 'Cuba', capital: 'Havana'),
  Country(name: 'Cyprus', capital: 'Nicosia'),
  Country(name: 'Czech Republic', capital: 'Prague'),
  Country(name: 'Denmark', capital: 'Copenhagen'),
  Country(name: 'Djibouti', capital: 'Djibouti'),
  Country(name: 'Dominica', capital: 'Roseau'),
  Country(name: 'Dominican Republic', capital: 'Santo Domingo'),
  Country(name: 'Ecuador', capital: 'Quito'),
  Country(name: 'Egypt', capital: 'Cairo'),
  Country(name: 'El Salvador', capital: 'San Salvador'),
  Country(name: 'England', capital: 'London'),
  Country(name: 'Equatorial Guinea', capital: 'Malabo'),
  Country(name: 'Eritrea', capital: 'Asmara'),
  Country(name: 'Estonia', capital: 'Tallinn'),
  Country(name: 'Eswatini', capital: 'Mbabane'),
  Country(name: 'Ethiopia', capital: 'Addis Ababa'),
  Country(name: 'Faroe Islands', capital: 'Torshavn'),
  Country(name: 'Fiji', capital: 'Suva'),
  Country(name: 'Finland', capital: 'Helsinki'),
  Country(name: 'France', capital: 'Paris'),
  Country(name: 'Gabon', capital: 'Libreville'),
  Country(name: 'Gambia', capital: 'Banjul'),
  Country(name: 'Georgia', capital: 'Tbilisi'),
  Country(name: 'Germany', capital: 'Berlin'),
  Country(name: 'Ghana', capital: 'Accra'),
  Country(name: 'Greece', capital: 'Athens'),
  Country(name: 'Grenada', capital: 'St. George\'s'),
  Country(name: 'Guatemala', capital: 'Guatemala City'),
  Country(name: 'Guinea', capital: 'Conakry'),
  Country(name: 'Guinea-Bissau', capital: 'Bissau'),
  Country(name: 'Guyana', capital: 'Georgetown'),
  Country(name: 'Haiti', capital: 'Port-au-Prince'),
  Country(name: 'Honduras', capital: 'Tegucigalpa'),
  Country(name: 'Hungary', capital: 'Budapest'),
  Country(name: 'Iceland', capital: 'Reykjavik'),
  Country(name: 'India', capital: 'New Delhi'),
  Country(name: 'Indonesia', capital: 'Jakarta'),
  Country(name: 'Iran', capital: 'Tehran'),
  Country(name: 'Iraq', capital: 'Baghdad'),
  Country(name: 'Ireland', capital: 'Dublin'),
  Country(name: 'Israel', capital: 'Jerusalem'),
  Country(name: 'Italy', capital: 'Rome'),
  Country(name: 'Jamaica', capital: 'Kingston'),
  Country(name: 'Japan', capital: 'Tokyo'),
  Country(name: 'Jordan', capital: 'Amman'),
  Country(name: 'Kazakhstan', capital: 'Astana'),
  Country(name: 'Kenya', capital: 'Nairobi'),
  Country(name: 'Kiribati', capital: 'South Tarawa'),
  Country(name: 'Kosovo', capital: 'Pristina'),
  Country(name: 'Kuwait', capital: 'Kuwait City'),
  Country(name: 'Kyrgyzstan', capital: 'Bishkek'),
  Country(name: 'Laos', capital: 'Vientiane'),
  Country(name: 'Latvia', capital: 'Riga'),
  Country(name: 'Lebanon', capital: 'Beirut'),
  Country(name: 'Lesotho', capital: 'Maseru'),
  Country(name: 'Liberia', capital: 'Monrovia'),
  Country(name: 'Libya', capital: 'Tripoli'),
  Country(name: 'Liechtenstein', capital: 'Vaduz'),
  Country(name: 'Lithuania', capital: 'Vilnius'),
  Country(name: 'Luxembourg', capital: 'Luxembourg'),
  Country(name: 'Madagascar', capital: 'Antananarivo'),
  Country(name: 'Malawi', capital: 'Lilongwe'),
  Country(name: 'Malaysia', capital: 'Kuala Lumpur'),
  Country(name: 'Maldives', capital: 'Malé'),
  Country(name: 'Mali', capital: 'Bamako'),
  Country(name: 'Malta', capital: 'Valletta'),
  Country(name: 'Marshall Islands', capital: 'Majuro'),
  Country(name: 'Mauritania', capital: 'Nouakchott'),
  Country(name: 'Mauritius', capital: 'Port Louis'),
  Country(name: 'Mexico', capital: 'Mexico City'),
  Country(name: 'Micronesia', capital: 'Palikir'),
  Country(name: 'Moldova', capital: 'Chișinău'),
  Country(name: 'Monaco', capital: 'Monaco'),
  Country(name: 'Mongolia', capital: 'Ulaanbaatar'),
  Country(name: 'Montenegro', capital: 'Podgorica'),
  Country(name: 'Morocco', capital: 'Rabat'),
  Country(name: 'Mozambique', capital: 'Maputo'),
  Country(name: 'Myanmar', capital: 'Naypyidaw'),
  Country(name: 'Namibia', capital: 'Windhoek'),
  Country(name: 'Nauru', capital: 'Yaren'),
  Country(name: 'Nepal', capital: 'Kathmandu'),
  Country(name: 'Netherlands', capital: 'Amsterdam'),
  Country(name: 'New Zealand', capital: 'Wellington'),
  Country(name: 'Nicaragua', capital: 'Managua'),
  Country(name: 'Niger', capital: 'Niamey'),
  Country(name: 'Nigeria', capital: 'Abuja'),
  Country(name: 'North Korea', capital: 'Pyongyang'),
  Country(name: 'North Macedonia', capital: 'Skopje'),
  Country(name: 'Northern Ireland', capital: 'Belfast'),
  Country(name: 'Norway', capital: 'Oslo'),
  Country(name: 'Oman', capital: 'Muscat'),
  Country(name: 'Pakistan', capital: 'Islamabad'),
  Country(name: 'Palau', capital: 'Ngerulmud'),
  Country(name: 'Palestine', capital: 'Ramallah'),
  Country(name: 'Panama', capital: 'Panama City'),
  Country(name: 'Papua New Guinea', capital: 'Port Moresby'),
  Country(name: 'Paraguay', capital: 'Asunción'),
  Country(name: 'Peru', capital: 'Lima'),
  Country(name: 'Philippines', capital: 'Manila'),
  Country(name: 'Poland', capital: 'Warsaw'),
  Country(name: 'Portugal', capital: 'Lisbon'),
  Country(name: 'Qatar', capital: 'Doha'),
  Country(name: 'Romania', capital: 'Bucharest'),
  Country(name: 'Russia', capital: 'Moscow'),
  Country(name: 'Rwanda', capital: 'Kigali'),
  Country(name: 'Saint Kitts and Nevis', capital: 'Basseterre'),
  Country(name: 'Saint Lucia', capital: 'Castries'),
  Country(name: 'Saint Vincent and the Grenadines', capital: 'Kingstown'),
  Country(name: 'Samoa', capital: 'Apia'),
  Country(name: 'San Marino', capital: 'San Marino'),
  Country(name: 'Sao Tome and Principe', capital: 'São Tomé'),
  Country(name: 'Saudi Arabia', capital: 'Riyadh'),
  Country(name: 'Scotland', capital: 'Edinburgh'),
  Country(name: 'Senegal', capital: 'Dakar'),
  Country(name: 'Serbia', capital: 'Belgrade'),
  Country(name: 'Seychelles', capital: 'Victoria'),
  Country(name: 'Sierra Leone', capital: 'Freetown'),
  Country(name: 'Singapore', capital: 'Singapore'),
  Country(name: 'Slovakia', capital: 'Bratislava'),
  Country(name: 'Slovenia', capital: 'Ljubljana'),
  Country(name: 'Solomon Islands', capital: 'Honiara'),
  Country(name: 'Somalia', capital: 'Mogadishu'),
  Country(name: 'South Africa', capital: 'Pretoria'),
  Country(name: 'South Korea', capital: 'Seoul'),
  Country(name: 'South Sudan', capital: 'Juba'),
  Country(name: 'Spain', capital: 'Madrid'),
  Country(name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte'),
  Country(name: 'Sudan', capital: 'Khartoum'),
  Country(name: 'Suriname', capital: 'Paramaribo'),
  Country(name: 'Sweden', capital: 'Stockholm'),
  Country(name: 'Switzerland', capital: 'Bern'),
  Country(name: 'Syria', capital: 'Damascus'),
  Country(name: 'Taiwan', capital: 'Taipei'),
  Country(name: 'Tajikistan', capital: 'Dushanbe'),
  Country(name: 'Tanzania', capital: 'Dodoma'),
  Country(name: 'Thailand', capital: 'Bangkok'),
  Country(name: 'Timor-Leste', capital: 'Dili'),
  Country(name: 'Togo', capital: 'Lomé'),
  Country(name: 'Tonga', capital: 'Nuku\'alofa'),
  Country(name: 'Trinidad and Tobago', capital: 'Port of Spain'),
  Country(name: 'Tunisia', capital: 'Tunis'),
  Country(name: 'Turkey', capital: 'Ankara'),
  Country(name: 'Turkmenistan', capital: 'Ashgabat'),
  Country(name: 'Tuvalu', capital: 'Funafuti'),
  Country(name: 'Uganda', capital: 'Kampala'),
  Country(name: 'Ukraine', capital: 'Kyiv'),
  Country(name: 'United Arab Emirates', capital: 'Abu Dhabi'),
  Country(name: 'United Kingdom', capital: 'London'),
  Country(name: 'United States', capital: 'Washington, D.C.'),
  Country(name: 'Uruguay', capital: 'Montevideo'),
  Country(name: 'Uzbekistan', capital: 'Tashkent'),
  Country(name: 'Vanuatu', capital: 'Port Vila'),
  Country(name: 'Vatican City', capital: 'Vatican City'),
  Country(name: 'Venezuela', capital: 'Caracas'),
  Country(name: 'Vietnam', capital: 'Hanoi'),
  Country(name: 'Wales', capital: 'Cardiff'),
  Country(name: 'Yemen', capital: 'Sana\'a'),
  Country(name: 'Zambia', capital: 'Lusaka'),
  Country(name: 'Zimbabwe', capital: 'Harare'),
];